### ISSUE TITLE
[REQ] Use a small button instead of displaying the video address directly

### ISSUE THREAD

**Issue by waldens** [AnonymousMeerkat/inject2download#3]
The current way, that video URLs are displayed directly, often blocks page content and disturbs reading, which is probably why [some users suggest the implementation of the blacklist feature](https://greasyfork.org/zh-CN/forum/discussion/29318/). However, I don't think blacklist is the best way to solve this issue, because there are too many sites need to add manually.

Would you please consider a feature request? Use a small button instead of displaying the video address directly, and then expand the button to display all the video addresses when the mouse hovers it?

![](http://onuia4d7l.bkt.clouddn.com/2018_01_12_20180112063711.png)

Like this design, expand the button to display all the video addresses when the mouse hovers it:
[reference](https://greasyfork.org/zh-CN/scripts/6303-iciba%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/code)
![](http://onuia4d7l.bkt.clouddn.com/2018_01_12_2222.gif)

**Comment by AnonymousMeerkat** [comment]
Interesting idea! I completely agree with the idea that the box is annoying, I often find myself habitually closing it, definitely not a good thing.

I like the idea of selecting the video element to expand the dialog, but I'm not quite sure how easy it will be to translate this to every website (as well as deal with websites that disable selection for whatever reason, athough ctrl+a would possibly work there). I'm thinking it could possibly also have a modifier and/or shortcut, but then it could interfere with the site as well...

If you have any other ideas for design, please share, I completely agree that the current design is very frustrating, but it has stayed simply because I've been unable to find a better one so far.

**Comment by waldens** [comment]
Thanks for your quick reply! Pardon me if my request isn't clear enough, "changing the trigger timing to selecting the video element" isn't the feature I request, which I agree with you, makes the code logic more complicated.

This request is just about "WHAT to show", not about "WHEN to show". It's already good for me that WHEN the script detects the entire page has videos, it displays the content. However, I really love that, this content is no longer a long video address list, but just a tiny button.

**Comment by waldens** [comment]
Basically, like this: [reference](https://greasyfork.org/zh-CN/scripts/27530-%E7%A0%B4%E8%A7%A3vip%E4%BC%9A%E5%91%98%E8%A7%86%E9%A2%91%E9%9B%86%E5%90%88/code)
![](http://onuia4d7l.bkt.clouddn.com/2018_01_13_2222.gif)

**Comment by AnonymousMeerkat** [comment]
Sorry for replying so late. I believe 882dfa482e066be0068794346678dc722bf77c00 fixes this, see if it works for you :)

**Comment by waldens** [comment]
Great! Exactly what I wanted. Thank you!
