### ISSUE TITLE
some issue in version 0.4.x

### ISSUE THREAD

**Issue by ale82to** [AnonymousMeerkat/inject2download#5]
both version 0.4.0 and 0.4.1
prevent thisvid.com video from playing at all reverting to version 0.3.3 everything's OK. please fix it
tested on Firefox for Android and violentmonkey.

**Comment by AnonymousMeerkat** [comment]
Sorry, I forgot to push the update! I'm pretty sure this should fix it.

I had rushed the 0.4 release a bit too much, since it was a complete rewrite of the injection system, I forgot to re-implement a few features. For this problem, although it ran the function, it didn't copy over previous properties into the new replacement, causing errors (and therefore, the entire video failing to run).

**Comment by ale82to** [comment]
thanks a lot problem fixed in new version !
