### ISSUE TITLE
Won't popup the download modal

### ISSUE THREAD

**Issue by GiovanH** [AnonymousMeerkat/inject2download#7]
Long timer user. 

Tried using it in soundcloud and youtube today, but the model never detected the audio or video in either website.

**Comment by AnonymousMeerkat** [comment]
This userscript is mainly meant for injecting commonly-used scripts, such as jwPlayer, not really for using proprietary websites, as other scripts such as `youtube-dl` (alongside many others) usually already support them.

As such, Youtube has never been supported. A few proprietary websites were supported a while ago, due to `youtube-dl` not properly supporting them at the time (soundcloud was among them).

With that being said though, I'll see if I can fix Soundcloud. It seems they just updated their API.
